AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TwitterAnalysis
  It returns the results of the Twitter keyword search and the analysis of the content with 'Amazon Comprehend'.
Globals:
  Function:
    Timeout: 300

Resources:
  TwitterAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: TwitterAnalysis/
      Handler: TwitterAnalysis
      Runtime: go1.x
      Tracing: Active
      Role: !GetAtt TwitterAnalysisFunctionIamRole.Arn
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /TwitterAnalysis
            Method: GET
      Environment:
        Variables:
          TWITTER_CONSUMER_KEY: [TWITTER_CONSUMER_KEY]
          TWITTER_CONSUMER_SECRET: [TWITTER_CONSUMER_SECRET]
          TWITTER_ACCESS_TOKEN: [TWITTER_ACCESS_TOKEN]
          TWITTER_ACCESS_SECRET: [TWITTER_ACCESS_SECRET]
  TwitterAnalysisFunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        - PolicyName: "twitter-analysis-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - comprehend:DetectSentiment
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                  - xray:GetSamplingRules
                  - xray:GetSamplingTargets
                  - xray:GetSamplingStatisticSummaries
                Resource: "*"
Outputs:
  TwitterAnalysisAPI:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/TwitterAnalysis/"
  TwitterAnalysisFunction:
    Value: !GetAtt TwitterAnalysisFunction.Arn
  TwitterAnalysisFunctionIamRole:
    Value: !GetAtt TwitterAnalysisFunction.Arn
